### ISSUE TITLE
LICENSE file

### ISSUE THREAD

**Issue by Eli-Black-Work** [alsotang/is-chinese#1]
Hello,

First off, thanks for sharing this project :)

I know that the project already says that the code is MIT licensed, but could you please also add a LICENSE file containing the text of the MIT license?

My understanding is that this may be necessary in order for the code to be considered legally licensed under MIT.

Babel recently went through something similar: https://github.com/babel/babel/pull/7308#issuecomment-367615152

**Comment by alsotang** [comment]
done

**Comment by Eli-Black-Work** [comment]
Wow, that was fast!

Thanks, man :)

Could you please push out a new version to NPM, too?

**Comment by alsotang** [comment]
ok
