### ISSUE TITLE
false results

### ISSUE THREAD

**Issue by dcsan** [alsotang/is-chinese#2]
你要吃什么吗？ isChinese: false

the chinese punctutaion mark is outside your range?

zh: ？
en: ?

**Comment by alsotang** [comment]
It is a bug. Because I don't judge the punctuation of Chinese.
I will add it sooner.

**Comment by alsotang** [comment]
punctuation judge added.
Please update version to 1.2.7

**Comment by dcsan** [comment]
cool, thanks!
at the moment I am just using something like this:

```
  isChinese (text) {
    if (!text) {
      debug.error('isChinese but no text')
      return false
    }
    let rex = /[\u3040-\u30ff\u3400-\u4dbf\u4e00-\u9fff\uf900-\ufaff\uff66-\uff9f]/
    if (text.match(rex)) {
      return true
    }
    return false
  }
```

can you explain a bit what your plugin does that is better? a more accurate range? I looked at all the specific code points you have added and it looks a lot more complex.

also, does this detect korean or japanese or are you more accurate in only detecting chinese?

And, I think your plugin the string has to be ALL chinese, a "contains chinese" feature might be nice...

**Comment by alsotang** [comment]
You can use implement your "contains chinese" feature easily.

**Comment by alsotang** [comment]
And I only interest in detect Chinese. Perhaps my Chinese Unicode is more complete. 
I use the ranges in Wikipedia. I even don't know exactly what those ranges are. It is complex to me too.
