### ISSUE TITLE
browserify as devDependency

### ISSUE THREAD

**Issue by Eli-Black-Work** [alsotang/is-chinese#3]
Hi alsotang,

Could you please put the `browserify` module in `devDependencies` instead of `dependencies`, so that people who use the `is-chinese` module don't also automatically download browserify?

Thanks :)

**Comment by alsotang** [comment]
@Bosch-Eli-Black sorry, my fault. Already fix this. 
bump version to 1.2.9

**Comment by Eli-Black-Work** [comment]
@alsotang No worries; thanks :)
